[package]
name = "libbun-runtime-native"
version = "0.2.3"
edition = "2024"
license = "Apache-2.0"
publish = false
build = "build.rs"

[[bin]]
name = "libbun-runtime-native"
path = "src/main.rs"

[dependencies]
libbun-native = { path = "../native", features = ["internal-adapter"] }
libbun-prepared-export-wire = { path = "../wire" }

[target.'cfg(target_os = "linux")'.dependencies]
bun_platform = { path = "../vendor/bun/src/platform" }
