[package]
name = "ss-runtime-provider-host-set-owner"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
swarm-capability-model.workspace = true
swarm-provider-host-set.workspace = true
swarm-rust-sdk-static-provider-host.workspace = true
swarm-substrate-invariant.workspace = true
thiserror.workspace = true

[lints]
workspace = true
